version: '3.6'

services:
  postgres:
    container_name: heat_postgres
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - env

  pgadmin:
    container_name: heat_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - env
    ports:
      - 6543:80
    depends_on:
      - postgres

volumes:
  pg_data: